DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = opo3tx

all: $(CONTIKI_PROJECT)
TARGETDIRS += ../../platform

SMALL = 0

CONTIKI = /home/wwhuang/Dropbox/git/contiki
include $(CONTIKI)/Makefile.include
