DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = spi-test

all: $(CONTIKI_PROJECT)
TARGETDIRS += ../../platform

CONTIKI = /home/wwhuang/Dropbox/git/contiki
include $(CONTIKI)/Makefile.include
