DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = null-power-test

TARGETDIRS += ../../platform/

all: $(CONTIKI_PROJECT)

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
