#include "contiki.h"
#include "board.h"
#include "dev/gpio.h"
#include "rf_switch.h"


void rf_switch_init() {
	GPIO_SOFTWARE_CONTROL(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
	GPIO_SET_OUTPUT(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
	GPIO_CLR_PIN(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
}

void ble_ant_enable() {
	GPIO_SOFTWARE_CONTROL(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
	GPIO_SET_OUTPUT(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
	GPIO_CLR_PIN(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
}

void cc2538_ant_enable() {
	GPIO_SET_PIN(RADIO_SELECT_PORT, RADIO_SELECT_PIN);
}


