DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = flash-test

all: $(CONTIKI_PROJECT)
TARGETDIRS += ../../platform

SMALL = 0

CONTIKI = ../../../../contiki
include $(CONTIKI)/Makefile.include
