#include "dev/gptimer.h"
#include "dev/gpio.h"
#include "dev/ioc.h"
#include "opo_helper.h"
#include "contiki.h"

void setup_opo_pwm() {
	ungate_gpt(1);
	gpt_set_16_bit_timer(1);
	gpt_set_mode(GPTIMER_1, GPTIMER_SUBTIMER_A, GPTIMER_PERIODIC_MODE);
	gpt_set_alternate_mode(GPTIMER_1, GPTIMER_SUBTIMER_A, GPTIMER_ALTERNATE_MODE_PWM);
	gpt_set_interval_value(GPTIMER_1, GPTIMER_SUBTIMER_A, 0x190);
	gpt_set_match_value(1, GPTIMER_SUBTIMER_A, 0xC8);
	ioc_set_sel(OPO_PWM_PORT_NUM, OPO_PWM_PIN_NUM, IOC_PXX_SEL_GPT1_ICP1);
  	ioc_set_over(OPO_PWM_PORT_NUM, OPO_PWM_PIN_NUM, IOC_OVERRIDE_OE);
  	GPIO_PERIPHERAL_CONTROL(OPO_PWM_PORT_BASE, OPO_PWM_PIN_MASK);
}

void setup_opo_timer_cap() {
	ungate_gpt(GPTIMER_1);
	gpt_set_16_bit_timer(GPTIMER_1);

	gpt_set_mode(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_CAPTURE_MODE);
	gpt_set_capture_mode(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_CAPTURE_MODE_EDGE_TIME);
	gpt_set_alternate_mode(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_ALTERNATE_MODE_CAPTURE);
	gpt_set_count_dir(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_COUNT_DIR_UP);
	gpt_set_event_mode(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_EVENT_MODE_POSITIVE_EDGE);
	gpt_enable_interrupt(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_CAPTURE_EVENT_INT);
	gpt_enable_interrupt(GPTIMER_1, GPTIMER_SUBTIMER_B, GPTIMER_TIMEOUT_EVENT);
	REG(IOC_GPT1OCP2) = OPO_GPT_COMP1_PIN; // Integrator, PC7, pin 23
}

void setup_opo_ul_rx_pins() {
	GPIO_SET_INPUT(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
	ioc_set_over(OPO_COMP1_PORT_NUM, OPO_COMP1_PIN_NUM, IOC_OVERRIDE_DIS);
	GPIO_DETECT_EDGE(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
	GPIO_TRIGGER_SINGLE_EDGE(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
	GPIO_DETECT_RISING(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);

	GPIO_SET_INPUT(OPO_INT_PORT_BASE, OPO_INT_PIN_MASK);
	ioc_set_over(OPO_INT_PORT_NUM, OPO_INT_PIN_NUM, IOC_OVERRIDE_DIS);
	GPIO_DETECT_EDGE(OPO_INT_PORT_BASE, OPO_INT_PIN_MASK);
	GPIO_TRIGGER_SINGLE_EDGE(OPO_INT_PORT_BASE, OPO_INT_PIN_MASK);
	GPIO_DETECT_RISING(OPO_INT_PORT_BASE, OPO_INT_PIN_MASK);

  	GPIO_SET_INPUT(OPO_COMP2_PORT_BASE, OPO_COMP2_PIN_MASK);
  	ioc_set_over(OPO_COMP2_PORT_NUM, OPO_COMP2_PIN_NUM, IOC_OVERRIDE_DIS);
  	GPIO_DETECT_EDGE(OPO_COMP2_PORT_BASE, OPO_COMP2_PIN_MASK);
	GPIO_TRIGGER_SINGLE_EDGE(OPO_COMP2_PORT_BASE, OPO_COMP2_PIN_MASK);
	GPIO_DETECT_RISING(OPO_COMP2_PORT_BASE, OPO_COMP2_PIN_MASK);
}

void enable_opo_comp1_int() {
	GPIO_ENABLE_INTERRUPT(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
}

void enable_opo_comp2_int() {
	GPIO_ENABLE_INTERRUPT(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
}

void enable_opo_integrator_int() {
	GPIO_ENABLE_INTERRUPT(OPO_COMP1_PORT_BASE, OPO_COMP1_PIN_MASK);
}

void opo_init() {
	setup_opo_pwm();
	setup_opo_timer_cap();
	setup_opo_ul_rx_pins();
	nvic_interrupt_enable(OPO_COMP1_NVIC);
    nvic_interrupt_enable(NVIC_INT_GPTIMER_1B);
}

void enable_opo_ul_rx() {
	GPIO_SET_OUTPUT(OPO_TX_RX_SEL_PORT_BASE, OPO_TX_RX_SEL_PIN_MASK);
  	GPIO_CLR_PIN(OPO_TX_RX_SEL_PORT_BASE, OPO_TX_RX_SEL_PIN_MASK);
}

void enable_opo_ul_tx() {
	GPIO_SET_OUTPUT(OPO_TX_RX_SEL_PORT_BASE, OPO_TX_RX_SEL_PIN_MASK);
  	GPIO_SET_PIN(OPO_TX_RX_SEL_PORT_BASE, OPO_TX_RX_SEL_PIN_MASK);
}